services:
  bd_inventory:
    image: postgres:15
    container_name: bd_inventory
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
    ports:
      - "9998:5432"
    volumes:
      - postgres_inventory:/var/lib/postgresql/data

  bd_venta:
    image: postgres:15
    container_name: bd_venta
    environment:
      POSTGRES_DB: venta_db
      POSTGRES_USER: venta_user
      POSTGRES_PASSWORD: venta_pass
    ports:
      - "9997:5432"
    volumes:
      - postgres_venta:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  kafka-setup:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [kafka]
    command: >
      bash -c "kafka-topics --create --if-not-exists --topic venta-realizada --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1"

  venta_service:
    build:
      context: ./venta-service
      dockerfile: dockerfile
    container_name: venta_service
    ports:
      - "5152:5152"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5152
    depends_on:
      - bd_venta

  inventory_service:
    build:
      context: ./demo
      dockerfile: dockerfile
    container_name: inventory_service
    ports:
      - "5000:5000"
    depends_on:
      - bd_inventory

  inventoryapp:
    container_name: inventory_app
    build: ./my-inventory-app
    ports:
      - "80:80"

volumes:
  postgres_inventory:
  postgres_venta:
