# Imagen base runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80

# Build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["venta-service.csproj", "./"]
RUN dotnet restore "venta-service.csproj"

COPY . .
RUN dotnet build "venta-service.csproj" -c Release -o /app/build

# Publish
FROM build AS publish
RUN dotnet publish "venta-service.csproj" -c Release -o /app/publish

# Final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "venta-service.dll"]