spring.application.name=demo

# Puerto del servidor
server.port=5000

# Configuración PostgreSQL
spring.datasource.url=jdbc:postgresql://bd:5432/ejemplo_db
spring.datasource.username=ejemplo_user
spring.datasource.password=ejemplo_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=producto-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Hikari
# 5 conexiones abiertas minimo
spring.datasource.hikari.minimum-idle=5
# timeout en ms (5 s)
spring.datasource.hikari.connection-timeout=5000
# aca 10 s
spring.datasource.hikari.idle-timeout=10000
# 180 s y mata las conexiones
spring.datasource.hikari.max-lifetime=180000
# maximo de conexiones
spring.datasource.hikari.maximum-pool-size=10